### ISSUE TITLE
Tensorflow bionic (18.04) 2.4.0 package link is incorrect

### ISSUE THREAD

**Issue by ShamoX** [Qengineering/TensorFlow-Raspberry-Pi_64-bit#7]
Hello,

I've made a [little repository](https://gitlab.com/liant-sasu/multiarch-tensorflow) with all your builds and I was getting all the wheels, and found out that the link for the version 2.4.0 of the package on the line of Ubuntu 18.04 is giving the version 2.3.1 of the package instead of 2.4.0.

Best.

**Comment by Qengineering** [comment]
@ShamoX ,

Slip of the tongue. Restored with the correct link.
